const ADD_ACTIVITY    = 'ADD_ACTIVITY';
const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY'
const EDIT_ACTIVITY   = 'EDIT_ACTIVITY'

const ACTIVITY = {
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  REMOVE_ACTIVITY
};

Object.freeze(ACTIVITY);

export { ACTIVITY };
