const ADD_ACTIVITY    = 'ADD_ACTIVITY';
const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
const EDIT_ACTIVITY   = 'EDIT_ACTIVITY';
const OPEN_MANAGER    = 'OPEN_MANAGER';
const CLOSE_MANAGER   = 'CLOSE_MANAGER';



const ACTIVITY = {
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  REMOVE_ACTIVITY,
  OPEN_MANAGER,
  CLOSE_MANAGER
};

Object.freeze(ACTIVITY);

export { ACTIVITY };
