const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
const FILTER_ACTIVETIES = 'FILTER_ACTIVETIES';
const ADD_ACTIVITY = 'ADD_ACTIVITY';

const DATABASE = {
  CREATE_ACTIVITY,
  FILTER_ACTIVETIES,
  ADD_ACTIVITY
};

Object.freeze(DATABASE);

export { DATABASE };
