const NAVIGATE_FORWARD    = 'NAVIGATE_FORWARD';
const NAVIGATE_BACKWARDS  = 'NAVIGATE_BACKWARDS'

const NAVIGATION = {
  NAVIGATE_FORWARD,
  NAVIGATE_BACKWARDS
};

Object.freeze(NAVIGATION);

export { NAVIGATION };
